# Generated by Django 5.2.6 on 2025-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('random', 'Random'), ('jersey', 'Jersey'), ('bola', 'Bola')], default='random', max_length=50),
        ),
    ]
